import type { CaseQueueItem, EvidenceItem, GraphEdge, GraphNode, TimelineEvent } from "./types";

export const demoCaseQueue: readonly CaseQueueItem[] = [
  { id: "EG-2026-0147", name: "Project Meridian", cue: "Layering · Crypto off-ramp", risk: 87, age: "18m" },
  { id: "EG-2026-0139", name: "Northstar", cue: "Trade finance · UBO", risk: 74, age: "2h" },
  { id: "EG-2026-0128", name: "Amber Route", cue: "Sanctions · Shipping", risk: 68, age: "1d" },
];

export const nodes: GraphNode[] = [
  { id: "elena", label: "Elena Kovac", detail: "Person · EE", kind: "person", x: 145, y: 68 },
  {
    id: "nova",
    label: "Nova Meridian Ltd",
    detail: "Company · EE",
    kind: "company",
    x: 250,
    y: 210,
    risk: true,
  },
  {
    id: "orion",
    label: "Orion Trade GmbH",
    detail: "Company · DE",
    kind: "company",
    x: 510,
    y: 210,
    risk: true,
  },
  {
    id: "wallet",
    label: "Wallet 0x7A…91F",
    detail: "Crypto wallet",
    kind: "wallet",
    x: 760,
    y: 210,
    risk: true,
  },
  {
    id: "bank",
    label: "Alpine Bank AG",
    detail: "Account · CH",
    kind: "account",
    x: 210,
    y: 405,
  },
  {
    id: "helix",
    label: "Helix Trading FZE",
    detail: "Company · AE",
    kind: "company",
    x: 505,
    y: 420,
  },
  {
    id: "dubai",
    label: "Dubai",
    detail: "Jurisdiction · AE",
    kind: "jurisdiction",
    x: 640,
    y: 420,
  },
  {
    id: "tornado",
    label: "Tornado Cash",
    detail: "Mixer service",
    kind: "service",
    x: 930,
    y: 210,
  },
];

export const edges: GraphEdge[] = [
  {
    id: "e1",
    source: "elena",
    target: "nova",
    label: "Beneficial owner",
    confidence: 91,
    evidenceIds: ["E-024"],
    rationale: "Registry ownership disclosure links Elena Kovac to Nova Meridian Ltd.",
  },
  {
    id: "e2",
    source: "bank",
    target: "nova",
    label: "USD 2.4M",
    detail: "May 12, 2026",
    confidence: 98,
    evidenceIds: ["E-018"],
    rationale: "Authenticated SWIFT record establishes the inbound transfer.",
  },
  {
    id: "e3",
    source: "nova",
    target: "orion",
    label: "USD 2.38M",
    detail: "May 14, 2026",
    suspicious: true,
    confidence: 94,
    evidenceIds: ["E-018", "E-021", "E-024"],
    rationale:
      "Forms the middle leg of a 72-hour circular flow through a trade counterparty before conversion to crypto.",
  },
  {
    id: "e4",
    source: "orion",
    target: "wallet",
    label: "USDT 2.31M",
    detail: "May 16, 2026",
    suspicious: true,
    confidence: 96,
    evidenceIds: ["E-021", "E-027"],
    rationale:
      "The invoice amount and on-chain settlement align within 2.9%, with no matching shipping record.",
  },
  {
    id: "e5",
    source: "orion",
    target: "helix",
    label: "Related party",
    confidence: 83,
    evidenceIds: ["E-024"],
    rationale: "Both companies share a registered formation agent and contact number.",
  },
  {
    id: "e6",
    source: "orion",
    target: "dubai",
    label: "Uses same agent",
    confidence: 88,
    evidenceIds: ["E-024"],
    rationale: "Corporate registry extract identifies the same Dubai-based formation agent.",
  },
  {
    id: "e7",
    source: "wallet",
    target: "tornado",
    label: "Interacts with",
    confidence: 99,
    evidenceIds: ["E-027"],
    rationale: "On-chain trace resolves a direct interaction with the mixer contract.",
  },
];

export const evidence: EvidenceItem[] = [
  {
    id: "E-018",
    title: "SWIFT MT103",
    source: "Deutsche Bank",
    date: "May 14, 2026",
    hash: "a3f9c2…7e1d",
    locator: "p. 1 · bbox 112,84,904,286",
    kind: "transaction",
    verifiedBy: "Sarah Chen",
  },
  {
    id: "E-021",
    title: "Invoice #INV-8841",
    source: "Orion Trade GmbH",
    date: "May 13, 2026",
    hash: "b7d4e0…9c2a",
    locator: "pp. 2–3 · bbox 64,190,918,622",
    kind: "document",
    verifiedBy: "Daniel Kim",
  },
  {
    id: "E-024",
    title: "Registry extract",
    source: "Estonian Business Register",
    date: "May 10, 2026",
    hash: "c9e1b2…6f3d",
    locator: "p. 1 · entity span 4",
    kind: "registry",
    verifiedBy: "Marta Silva",
  },
  {
    id: "E-027",
    title: "Blockchain transfer",
    source: "Ethereum",
    date: "May 16, 2026",
    hash: "4f88a1…91fc",
    locator: "block 22,841,906 · tx 0x7a…91f",
    kind: "blockchain",
    verifiedBy: "Chainalysis feed",
  },
];

export const timeline: TimelineEvent[] = [
  {
    id: "t1",
    date: "May 12",
    time: "09:14",
    title: "USD 2.4M received",
    detail: "Alpine Bank AG → Nova Meridian Ltd",
    kind: "transaction",
  },
  {
    id: "t2",
    date: "May 13",
    time: "10:21",
    title: "Invoice ingested",
    detail: "INV-8841 · E-021",
    kind: "document",
  },
  {
    id: "t3",
    date: "May 14",
    time: "10:24",
    title: "USD 2.38M transferred",
    detail: "Nova Meridian Ltd → Orion Trade GmbH",
    kind: "transaction",
  },
  {
    id: "t4",
    date: "May 14",
    time: "18:32",
    title: "Risk spike",
    detail: "Circular flow threshold exceeded",
    kind: "risk",
  },
  {
    id: "t5",
    date: "May 16",
    time: "11:03",
    title: "USDT 2.31M settled",
    detail: "Orion Trade GmbH → Wallet 0x7A…91F",
    kind: "transaction",
  },
  {
    id: "t6",
    date: "May 18",
    time: "16:08",
    title: "Path hypothesis proposed",
    detail: "AI run AIR-019 · review required",
    kind: "ai",
  },
  {
    id: "t7",
    date: "May 19",
    time: "09:42",
    title: "Human verification",
    detail: "Evidence stack independently verified",
    kind: "review",
  },
];
