import type { EvidenceItem, GraphEdge, GraphNode, TimelineEvent } from "./types";

export const nodes: GraphNode[] = [
  { id: "elena", label: "Elena Kovac", detail: "Person", kind: "person", x: 145, y: 68 },
  {
    id: "nova",
    label: "Nova Meridian Ltd",
    detail: "Company",
    kind: "company",
    x: 250,
    y: 210,
    risk: true,
  },
  {
    id: "orion",
    label: "Orion Trade GmbH",
    detail: "Company",
    kind: "company",
    x: 510,
    y: 210,
    risk: true,
  },
  {
    id: "wallet",
    label: "Wallet 0x7A…91F",
    detail: "Crypto wallet",
    kind: "wallet",
    x: 760,
    y: 210,
    risk: true,
  },
  {
    id: "bank",
    label: "Alpine Bank AG",
    detail: "Bank account",
    kind: "account",
    x: 210,
    y: 405,
  },
  {
    id: "helix",
    label: "Helix Trading FZE",
    detail: "Company",
    kind: "company",
    x: 505,
    y: 420,
  },
  {
    id: "dubai",
    label: "Dubai",
    detail: "Jurisdiction",
    kind: "jurisdiction",
    x: 640,
    y: 420,
  },
  {
    id: "tornado",
    label: "Tornado Cash",
    detail: "Service",
    kind: "service",
    x: 930,
    y: 210,
  },
];

export const edges: GraphEdge[] = [
  { id: "e1", source: "elena", target: "nova", label: "Beneficial owner" },
  {
    id: "e2",
    source: "bank",
    target: "nova",
    label: "USD 2.4M",
    detail: "May 12, 2026",
  },
  {
    id: "e3",
    source: "nova",
    target: "orion",
    label: "USD 2.38M",
    detail: "May 14, 2026",
    suspicious: true,
  },
  {
    id: "e4",
    source: "orion",
    target: "wallet",
    label: "USDT 2.31M",
    detail: "May 16, 2026",
    suspicious: true,
  },
  { id: "e5", source: "orion", target: "helix", label: "Related party" },
  { id: "e6", source: "orion", target: "dubai", label: "Uses same agent" },
  { id: "e7", source: "wallet", target: "tornado", label: "Interacts with" },
];

export const evidence: EvidenceItem[] = [
  {
    id: "E-018",
    title: "SWIFT MT103",
    source: "Deutsche Bank",
    date: "May 14, 2026",
    hash: "a3f9c2…7e1d",
    locator: "p. 1 · bbox 112,84,904,286",
  },
  {
    id: "E-021",
    title: "Invoice #INV-8841",
    source: "Orion Trade GmbH",
    date: "May 13, 2026",
    hash: "b7d4e0…9c2a",
    locator: "pp. 2–3 · bbox 64,190,918,622",
  },
  {
    id: "E-024",
    title: "Registry extract",
    source: "Estonian Business Register",
    date: "May 10, 2026",
    hash: "c9e1b2…6f3d",
    locator: "p. 1 · entity span 4",
  },
  {
    id: "E-027",
    title: "Blockchain transfer",
    source: "Ethereum",
    date: "May 16, 2026",
    hash: "0x7a…91f",
    locator: "block 22,841,906",
  },
];

export const timeline: TimelineEvent[] = [
  {
    id: "t1",
    date: "May 12",
    time: "09:14",
    title: "USD 2.4M",
    detail: "Nova Meridian Ltd → Alpine Bank AG",
    kind: "transaction",
  },
  {
    id: "t2",
    date: "May 13",
    time: "10:21",
    title: "Invoice ingested",
    detail: "INV-8841 · E-021",
    kind: "document",
  },
  {
    id: "t3",
    date: "May 14",
    time: "10:24",
    title: "USD 2.38M",
    detail: "Nova Meridian Ltd → Orion Trade GmbH",
    kind: "transaction",
  },
  {
    id: "t4",
    date: "May 14",
    time: "18:32",
    title: "Risk spike",
    detail: "Circular transfer pattern detected",
    kind: "risk",
  },
  {
    id: "t5",
    date: "May 16",
    time: "11:03",
    title: "USDT 2.31M",
    detail: "Orion Trade GmbH → Wallet 0x7A…91F",
    kind: "transaction",
  },
  {
    id: "t6",
    date: "May 19",
    time: "09:42",
    title: "Human verification",
    detail: "Evidence stack independently verified",
    kind: "review",
  },
];
